<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.janboerman.doubledoors</groupId>
    <artifactId>double-doors</artifactId>
    <version>1.3-SNAPSHOT</version>

    <name>DoubleDoors</name>

    <scm>
        <developerConnection>scm:git:ssh://git@github.com/Jannyboy11/DoubleDoors.git</developerConnection>
        <tag>v1.1</tag>
    </scm>

    <distributionManagement>
        <repository>
            <id>github-doubledoors</id>
            <name>GitHub Jannyboy11 Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/Jannyboy11/DoubleDoors</url>
        </repository>
        <snapshotRepository>
            <id>repsy</id>
            <name>Jannyboy11 Repsy Minecraft Repo</name>
            <url>https://repo.repsy.io/mvn/jannyboy11/minecraft</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <plugins>
            <!-- Maven Compiler Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.16.0</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>

            <!-- Maven Release Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>3.0.1</version>
                <configuration>
                    <tagNameFormat>v@{project.version}</tagNameFormat>
                    <preparationGoals>clean verify</preparationGoals>
                    <scmCommentPrefix>Maven Release Plugin:</scmCommentPrefix>
                    <scmReleaseCommitComment>@{prefix} Release @{releaseLabel}&#x1f389;!</scmReleaseCommitComment>
                    <scmDevelopmentCommitComment>@{prefix} Bump version.</scmDevelopmentCommitComment>
                    <scmRollbackCommitComment>@{prefix} Roll back.</scmRollbackCommitComment>
                </configuration>
            </plugin>

            <!-- Maven Javadoc Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.12.0</version>
                <configuration>
                    <!-- spigot api javadoc -->
                    <links>
                        <link>https://hub.spigotmc.org/javadocs/spigot/</link>
                    </links>

                    <!-- only show protected and public stuff -->
                    <show>protected</show>

                    <!-- who needs help, anyway? -->
                    <nohelp>true</nohelp>

                    <!-- the javadoc tool is too picky for me -->
                    <failOnError>false</failOnError>

                    <!-- so that proper hyperlinks to standard jdk classes are generated -->
                    <additionalOptions>-source 25</additionalOptions>
                </configuration>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.15.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>